# Display
name: PyrSlotMachine
description: 'Gamble easily with this nice machine.'
author: PYRRH4
website: www.pyrrh4.be
# Techy
version: 1.0.0
main: be.pyrrh4.pyrslotmachine.PyrSlotMachine
depend: [PyrCore]
# Commands
commands:
  machine:
    aliases: [slotmachine]
