# Display
name: PyrSlotMachine
description: 'Gamble easily with this nice machine.'
author: PYRRH4
website: www.pyrrh4.be
# Techy
version: 2.0.1-BETA
api-version: 1.13
main: be.pyrrh4.pyrslotmachine.PyrSlotMachine
depend: [PyrCore,Vault]
# Commands
commands:
  machine:
    aliases: [pyrslotmachine,slotmachine]
permissions:
  pyrslotmachine.admin:
    default: op
