#----------------------------------------------------------------------------------------------------
# Configuration file for PyrParticles
#----------------------------------------------------------------------------------------------------

# Machines types

types:
  gold:
    cost: 100.0
    prizes:
      1:
        type: GOLD_INGOT
        amount: 64
        chance: 50
