#----------------------------------------------------------------------------------------------------
# Configuration file for PyrParticles
#----------------------------------------------------------------------------------------------------

# Machines types

types:
  gold:
    cost: 100.0
    animation_sound: WOOD_CLICK
    win_sound: LEVEL_UP
    lose_sound: ANVIL_BREAK
    prizes:
      1:
        type: GOLD_INGOT
        amount: 16
        chance: 30
      2:
        type: DIAMOND
        amount: 1
        chance: 10
      3:
        type: QUARTZ
        amount: 32
        chance: 10
      4:
        type: COBBLESTONE
        amount: 64
        chance: 20
      5:
        type: APPLE
        amount: 16
        chance: 10
      6:
        type: DEAD_BUSH
        amount: 16
        chance: 10
      7:
        type: BONE
        amount: 16
        chance: 10
