#----------------------------------------------------------------------------------------------------
# Configuration file for PyrParticles
#----------------------------------------------------------------------------------------------------

# Locale

locale: pyrslotmachine_en_US.yml

#----------------------------------------------------------------------------------------------------
# Machines types
#----------------------------------------------------------------------------------------------------

types:
  gold:
    cost: 100.0
    prizes:
      1:
        type: GOLD_INGOT
        amount: 64
        chance: 50
